# Sprint Status Recovery Workflow
name: recover-sprint-status
description: "Recover sprint-status.yaml when tracking has drifted. Analyzes story files, git commits, and autonomous reports to rebuild accurate status."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/recover-sprint-status"
instructions: "{installed_path}/instructions.md"

# Inputs
variables:
  sprint_status_file: "{implementation_artifacts}/sprint-status.yaml"
  story_directory: "{implementation_artifacts}/sprint-artifacts"
  recovery_mode: "interactive" # Options: interactive, conservative, aggressive

# Recovery script location
recovery_script: "{project-root}/scripts/recover-sprint-status.sh"

# Standalone so IDE commands get generated
standalone: true

# No web bundle needed