name: validate-all-stories-deep
description: "Comprehensive platform audit using Haiku agents. Validates ALL stories by reading actual code. The bulletproof validation for production readiness."
author: "BMad"
version: "1.0.0"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/validate-all-stories-deep"
instructions: "{installed_path}/instructions.xml"

# Input variables
variables:
  epic_filter: "" # Optional: Only validate specific epic (e.g., "16e")
  batch_size: 5 # Validate 5 stories at a time (prevents spawning 511 agents at once!)
  concurrent_limit: 5 # Max 5 agents running concurrently
  auto_fix: false # If true, auto-update statuses based on validation
  pause_between_batches: 30 # Seconds to wait between batches (rate limiting)

# Sub-workflow
validate_story_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/validate-story-deep/workflow.yaml"

# Agent configuration
agent_model: "haiku" # Cost: ~$66 for 511 stories vs $793 with Sonnet

# Output
default_output_file: "{story_dir}/.comprehensive-audit-{date}.md"
progress_file: "{story_dir}/.validation-progress-{date}.yaml"

standalone: true