name: validate-story-deep
description: "Deep story validation using Haiku agents to read and verify actual code. Each task gets micro code review to verify implementation quality."
author: "BMad"
version: "1.0.0"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/validate-story-deep"
instructions: "{installed_path}/instructions.xml"

# Input variables
variables:
  story_file: "" # Path to story file to validate

# Agent configuration
agent_model: "haiku" # Use Haiku 4.5 for cost efficiency ($0.13/story vs $1.50)
parallel_tasks: true # Validate tasks in parallel (faster)

# Output
default_output_file: "{story_dir}/.validation-{story_id}-{date}.md"

standalone: true