epic_num: 4
started: 2026-01-03T07:47:58.832352Z
total_stories: 5
completed_stories: [4-4-document-version-history, 4-5-download-all-versions-as-zip]
current_story: 4-5-download-all-versions-as-zip
status: running
